---
apiVersion: batch/v1
kind: Job
metadata:
  name: es-imdb-indexing
spec:
  template:
    spec:
      containers:
        - name: imdb-indexing
          image: registry.ahamon.ovh/imdb-indexing:latest
          env:
            - name: ES_HOST
              value: 192.168.1.100
            - name: ES_PORT
              value: "30200"
          command: ["python", "-m", "index"]
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never